set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_FIXUP_ELF_RPATH ON)

list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON
)

string(APPEND VCPKG_C_FLAGS " -fPIC")
string(APPEND VCPKG_CXX_FLAGS " -fPIC")